CellRecharges/Controllers/ConsumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CellRecharges.Controllers
{
    public class ConsumeController : Controller
    {
        //
        // GET: /Consume/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CellRecharges/Controllers/CostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CellRecharges.Controllers
{
    public class CostController : Controller
    {
        //
        // GET: /Cost/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CellRecharges/Controllers/CurBalanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CellRecharges.Controllers
{
    public class CurBalanceController : Controller
    {
        //
        // GET: /CurBalance/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CellRecharges/Controllers/RechargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CellRecharges.Controllers
{
    public class RechargeController : Controller
    {
        //
        // GET: /Recharge/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CellRecharges/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Procesos</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Recargas a celulares", "Index", "Recharge", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Crear consumo", "Index", "Consume", new { area = "" }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultas</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Consulta de saldo actual", "Index", "CurBalance", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Historial de recargas", "Index", "RelHistory", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Historial de consumo", "Index", "ConsHistory", new { area = "" }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Parametrización</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Crear nuevo costo", "Index", "Cost", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Ver parametrización actual", "Index", "CurParametrization", new { area = "" }, null)</li>
                        </ul>
                    </li> 
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>